define_directive {v:work.fm_radio} {syn_black_box} {1}
define_directive {v:work.fm_radio} {.distcomp_black_box} {1}
define_directive {v:work.fm_radio} {.noprune} {1}
define_directive {v:work.fm_radio} {.distcompnoprune} {1}
define_directive {v:work.fm_radio_top} {.noprune} {1}
define_directive {v:work.fm_radio_top} {.distcompnoprune} {1}
define_directive {v:work.sync_fifo} {.noprune} {1}
define_directive {v:work.sync_fifo} {.distcompnoprune} {1}
define_directive {v:work.fm_radio_top} {.distcompmodetop} {1}
